"""Pydantic v2 schemas for compliance, agent outputs, and database serialization."""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class IssueItem(BaseModel):
    """Structured compliance issue detected by the Judge Agent."""
    issue_type: str = Field(..., description="Category: CONTRADICTION, FABRICATED_POLICY, UNSUPPORTED_NUMERICAL, MISSING_EVIDENCE, UNSUPPORTED_FACT, SOURCE_MISMATCH")
    description: str = Field(..., description="Clear explanation of the violation")
    severity: str = Field(default="HIGH", description="Severity: CRITICAL, HIGH, MEDIUM, LOW")
    claim_text: str = Field(default="", description="The offending claim in the draft")
    evidence_ref: Optional[str] = Field(default=None, description="Quoted snippet from verified knowledge base or 'NONE'")
    source: Optional[str] = Field(default=None, description="Source chunk ID or document reference where mismatch occurred")

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    def __init__(self, **data: Any):
        if "claim" in data and not data.get("claim_text"):
            data["claim_text"] = data["claim"]
        if "evidence" in data and not data.get("evidence_ref"):
            data["evidence_ref"] = data["evidence"]
        super().__init__(**data)

    @property
    def claim(self) -> str:
        return self.claim_text

    @property
    def evidence(self) -> Optional[str]:
        return self.evidence_ref


class MakerOutput(BaseModel):
    """Output generated by Agent 1 (Maker)."""
    draft_answer: str = Field(..., description="Draft answer formulated by Maker")
    sources: List[str] = Field(default_factory=list, description="List of source chunk IDs or document references")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Self-assessed confidence score")

    model_config = ConfigDict(from_attributes=True)


class JudgeOutput(BaseModel):
    """Output generated by Agent 2 (Judge)."""
    approved: bool = Field(..., description="True if answer is verified and safe for delivery")
    score: int = Field(..., ge=0, le=100, description="Verification confidence score (0-100)")
    issues: List[IssueItem] = Field(default_factory=list, description="List of detected compliance issues")

    model_config = ConfigDict(from_attributes=True)


class CorrectionOutput(BaseModel):
    """Output generated by Agent 3 (Correction)."""
    corrected_answer: str = Field(..., description="Rewritten answer using only verified evidence")
    explanation: str = Field(..., description="Explanation of what was removed or corrected")

    model_config = ConfigDict(from_attributes=True)


class CorrectionResult(CorrectionOutput):
    """Encapsulates the Correction Agent's output."""
    corrections: List[str] = Field(default_factory=list, description="List of specific corrections made")


class AskRequest(BaseModel):
    """Payload for submitting a customer query to the compliance filter."""
    question: str = Field(..., min_length=1, max_length=2000, description="Customer question to evaluate")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Optional caller metadata or session tags")


class AskResponse(BaseModel):
    """Customer-facing response payload for POST /api/v1/ask."""
    request_id: str = Field(..., description="Unique request identifier")
    question: str = Field(..., description="Original customer question")
    status: str = Field(..., description="Compliance status: APPROVED or BLOCKED")
    approved: bool = Field(..., description="Whether final answer is verified and approved")
    answer: str = Field(..., description="Customer-facing final answer")
    sources: List[str] = Field(default_factory=list, description="List of cited verified source IDs")
    judge_score: Optional[int] = Field(default=None, description="Final Judge compliance score")
    correction_attempts: int = Field(default=0, description="Number of correction cycles performed")
    latency_ms: Optional[float] = Field(default=None, description="Total workflow processing latency")
    issues: List[IssueItem] = Field(default_factory=list, description="Issues detected during evaluation")

    model_config = ConfigDict(from_attributes=True)


class AuditTraceItem(BaseModel):
    """Sequential execution step record for explainability."""
    step_index: int
    step_name: str
    payload: Dict[str, Any]
    timestamp: datetime

    model_config = ConfigDict(from_attributes=True)


class ComplianceResponse(BaseModel):
    """Standard API response for a processed customer request."""
    request_id: str
    question: str
    status: str = Field(..., description="Status: APPROVED, BLOCKED, ERROR")
    approved: bool
    final_answer: str
    judge_score: Optional[int] = None
    retry_count: int = 0
    latency_ms: Optional[float] = None
    issues: List[IssueItem] = Field(default_factory=list)
    audit_trail: Optional[List[AuditTraceItem]] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class RequestRecordSchema(BaseModel):
    """Serialization schema for full Request ORM model."""
    id: str
    question: str
    maker_output: Optional[Dict[str, Any]] = None
    judge_score: Optional[int] = None
    approved: bool
    status: str
    retry_count: int
    final_answer: Optional[str] = None
    latency_ms: Optional[float] = None
    created_at: datetime
    hallucinations: List[IssueItem] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)
